"""
LOOM — integration gate.

PLAN.md §6.3: "After each merge, swap one stub for the real module and re-run the
suite." This file is that swap, automated.

Every real module is discovered by import and skipped if it has not landed yet, so
this suite is meaningful from the first merge and complete at the last. A real
module must satisfy exactly what the stub satisfied — same Protocol, same shapes,
same bounds — because every other team wrote their tests against the stub.

Owned by the integrator. Teams do not edit this file.
"""

from __future__ import annotations

import importlib
import inspect
from pathlib import Path

import pytest
import torch

import contracts as C
import stubs as S

ROOT = Path(__file__).resolve().parent.parent


# ═══════════════════════════════════════════════════════════════════════════
#  DISCOVERY
# ═══════════════════════════════════════════════════════════════════════════

def _try(module: str, *names: str):
    """Import the first of `names` that exists in `module`, else skip.

    Teams pick their own class names; the contract is the Protocol, not the
    spelling. Trying several keeps the gate from failing on a naming choice.
    """
    try:
        mod = importlib.import_module(module)
    except Exception as exc:                                 # not landed yet
        pytest.skip(f"{module} not importable: {type(exc).__name__}: {exc}")
    for n in names:
        obj = getattr(mod, n, None)
        if obj is not None:
            return obj
    # Fall back to any class in the module satisfying nothing in particular.
    pytest.skip(f"{module} has none of {names}")


def _instantiate(cls, **kw):
    """Construct with only the kwargs the signature actually accepts."""
    try:
        sig = inspect.signature(cls)
        ok = {k: v for k, v in kw.items() if k in sig.parameters}
        return cls(**ok)
    except Exception as exc:
        pytest.skip(f"cannot instantiate {cls.__name__}: {type(exc).__name__}: {exc}")


# ═══════════════════════════════════════════════════════════════════════════
#  B · BANK — the module every bound depends on
# ═══════════════════════════════════════════════════════════════════════════

def _bank():
    return _instantiate(_try("loom.model.bank", "OperatorBank", "Bank", "OperatorBankImpl"))


def test_real_bank_satisfies_protocol():
    assert isinstance(_bank(), C.Bank)


#: PLAN §4.B asks for 10k draws. mix() expands each draw to (K, D//2) twice, so
#: 10k at once is ~2 GiB per tensor and gets OOM-killed. Same coverage, chunked.
_DRAWS, _CHUNK = 10_000, 500


def test_real_bank_is_contractive():
    """The single most load-bearing invariant in the method."""
    bank = _bank()
    for _ in range(_DRAWS // _CHUNK):
        C.assert_contractive(bank, n=_CHUNK)


def test_real_bank_bias_is_bounded():
    bank = _bank()
    for _ in range(_DRAWS // _CHUNK):
        C.assert_bias_bounded(bank, n=_CHUNK)


def test_real_bank_step_shape_and_broadcast():
    bank = _bank()
    z = torch.randn(3, C.K, C.D)
    out = bank.step(S.sparse_simplex(3), z)
    assert out.shape == z.shape
    C.assert_belief(out)

    zc = torch.randn(3, 5, C.K, C.D)
    outc = bank.step(S.sparse_simplex(3, 5), zc)
    assert outc.shape == zc.shape


def test_real_rollout_matches_sequential_step():
    """Catches the affine-composition bug: composing (A2,b2) after (A1,b1) is
    (A2A1, A2b1+b2), so multiplying lambdas alone silently drops the bias."""
    bank = _bank()
    z0 = torch.randn(2, C.K, C.D)
    c = S.sparse_simplex(2, 1, C.DEPTH)

    manual = z0.unsqueeze(1)
    for d in range(C.DEPTH):
        manual = bank.step(c[:, :, d], manual)

    assert torch.allclose(bank.rollout(c, z0), manual, atol=1e-5)


def test_real_rollout_does_not_explode():
    bank = _bank()
    z0 = torch.randn(8, C.K, C.D)
    leaves = bank.rollout(S.sparse_simplex(8, 1, C.DEPTH), z0)
    bound = (C.RHO ** C.DEPTH) * z0.flatten(1).norm(dim=1) \
        + (1 - C.RHO ** C.DEPTH) / (1 - C.RHO) * C.B_MAX
    assert (leaves.squeeze(1).flatten(1).norm(dim=1) <= bound + 1e-3).all()


def test_real_bank_stays_bf16():
    bank = _bank().to(torch.bfloat16)
    z = torch.randn(2, C.K, C.D, dtype=torch.bfloat16)
    out = bank.step(S.sparse_simplex(2, dtype=torch.bfloat16), z)
    assert out.dtype == torch.bfloat16 and not out.is_complex()


# ═══════════════════════════════════════════════════════════════════════════
#  B · ESTIMATOR
# ═══════════════════════════════════════════════════════════════════════════

def test_real_estimator_shape_and_recurrence():
    cls = _try("loom.model.estimator", "Estimator", "BeliefEstimator", "PerceiverEstimator")
    est = _instantiate(cls, feat_dim=1152, embodiments=("libero_franka",))
    assert isinstance(est, C.Estimator)

    feats = S.make_obs_feats(b=2)
    z1 = est(feats, None)
    C.assert_belief(z1)
    assert z1.shape == (2, C.K, C.D)

    z2 = est(feats, z1)
    C.assert_belief(z2)
    assert not torch.allclose(z1, z2), "z_prev must actually condition the update"


# ═══════════════════════════════════════════════════════════════════════════
#  C · q_Δ, q_a, decoder
# ═══════════════════════════════════════════════════════════════════════════

def test_real_q_delta_on_simplex():
    q = _instantiate(_try("loom.heads.q_delta", "QDelta", "QDeltaHead"))
    assert isinstance(q, C.QDelta)
    c = q(torch.randn(4, C.K, C.D), torch.randn(4, C.K, C.D))
    C.assert_simplex(c)


def test_real_q_action_on_simplex():
    q = _instantiate(_try("loom.heads.q_action", "QAction", "QActionHead"),
                     embodiments=("libero_franka",))
    a = torch.randn(4, C.H_OP, 7)
    z = torch.randn(4, C.K, C.D)
    try:
        c = q(a, z, "libero_franka")
    except TypeError:
        c = q(a, z)
    C.assert_simplex(c)


def test_real_decoder_emits_h_op_not_h_plan():
    """One c = one operator = H_OP steps. A decoder that emits 32 trains fine
    and scores near zero."""
    dec = _instantiate(_try("loom.heads.decoder", "Decoder", "FlowDecoder"),
                       embodiments=("libero_franka",))
    z, c = torch.randn(3, C.K, C.D), S.sparse_simplex(3)
    try:
        a = dec(z, c, "libero_franka")
    except TypeError:
        a = dec(z, c)
    assert a.shape[-2] == C.H_OP and a.shape[-2] != C.H_PLAN
    C.assert_action_segment(a, "libero_franka")


# ═══════════════════════════════════════════════════════════════════════════
#  E · proposal — the inference path
# ═══════════════════════════════════════════════════════════════════════════

def _proposal():
    return _instantiate(_try("loom.heads.proposal", "Proposal", "ProposalHead",
                             "PlackettLuceProposal"), lang_dim=1152)


def test_real_proposal_satisfies_protocol():
    assert isinstance(_proposal(), C.Proposal)


def test_real_proposal_sample_on_simplex():
    p = _proposal()
    c = p.sample(torch.randn(2, C.K, C.D), torch.randn(2, 16, 1152), n=11)
    assert c.shape == (2, 11, C.M)
    C.assert_simplex(c)


def test_real_proposal_log_prob_is_negative_and_finite():
    p = _proposal()
    z, lang = torch.randn(3, C.K, C.D), torch.randn(3, 16, 1152)
    lp = p.log_prob(z, lang, p.sample(z, lang, n=1)[:, 0])
    assert lp.shape == (3,)
    assert torch.isfinite(lp).all() and (lp <= 0).all()


def test_real_proposal_argmax_is_deterministic():
    """R0 inference is `c <- argmax pi_c`, with no search. It must not wobble."""
    p = _proposal()
    z, lang = torch.randn(2, C.K, C.D), torch.randn(2, 16, 1152)
    fn = getattr(p, "argmax", None)
    if fn is None:
        pytest.skip("proposal has no argmax()")
    a, b = fn(z, lang), fn(z, lang)
    assert torch.allclose(a, b)
    C.assert_simplex(a)


# ═══════════════════════════════════════════════════════════════════════════
#  CROSS-MODULE — the paths that only exist once two teams have merged
# ═══════════════════════════════════════════════════════════════════════════

def test_proposal_into_real_bank_rollout():
    """The R3 search path end to end: pi_c samples, the real bank rolls out,
    and the leaf is still a valid bounded belief."""
    p, bank = _proposal(), _bank()
    z = torch.randn(2, C.K, C.D)
    lang = torch.randn(2, 16, 1152)

    seq = getattr(p, "sample_seq", None)
    if seq is None:
        pytest.skip("proposal has no sample_seq()")
    c_seq = seq(z, lang, n=8, depth=C.DEPTH)
    assert c_seq.shape == (2, 8, C.DEPTH, C.M)

    leaf = bank.rollout(c_seq, z)
    assert leaf.shape == (2, 8, C.K, C.D)
    C.assert_belief(leaf)


def test_q_delta_coefficients_drive_the_real_bank():
    """q_Delta's output must be directly usable by the bank — that is the whole
    point of putting both encoders on one simplex."""
    q = _instantiate(_try("loom.heads.q_delta", "QDelta", "QDeltaHead"))
    bank = _bank()
    z, zn = torch.randn(4, C.K, C.D), torch.randn(4, C.K, C.D)
    c = q(z, zn)
    C.assert_simplex(c)
    C.assert_belief(bank.step(c, z))


def test_decoder_segment_feeds_q_action_round_trip():
    """The realizability gate in search needs q_a(D_e(z,c), z) to typecheck."""
    dec = _instantiate(_try("loom.heads.decoder", "Decoder", "FlowDecoder"),
                       embodiments=("libero_franka",))
    q = _instantiate(_try("loom.heads.q_action", "QAction", "QActionHead"),
                     embodiments=("libero_franka",))
    z, c = torch.randn(2, C.K, C.D), S.sparse_simplex(2)
    try:
        a = dec(z, c, "libero_franka")
    except TypeError:
        a = dec(z, c)
    try:
        c_hat = q(a, z, "libero_franka")
    except TypeError:
        c_hat = q(a, z)
    C.assert_simplex(c_hat)


# ═══════════════════════════════════════════════════════════════════════════
#  STANDING RULES — grepped, because prose does not enforce itself
# ═══════════════════════════════════════════════════════════════════════════

def _sources() -> list[Path]:
    pkg = ROOT / "loom"
    return [p for p in pkg.rglob("*.py")] if pkg.exists() else []


def test_no_view_as_complex_anywhere():
    """PLAN §9: there is no complex-bf16 dtype and the whole run is bf16."""
    bad = [p for p in _sources() if "view_as_complex" in p.read_text()]
    assert not bad, f"view_as_complex found in {[str(p.relative_to(ROOT)) for p in bad]}"


def test_no_compose_on_the_bank():
    """PLAN §9: multiplying lambdas alone silently discards the bias."""
    bank_py = ROOT / "loom" / "model" / "bank.py"
    if not bank_py.exists():
        pytest.skip("bank.py not landed")
    src = bank_py.read_text()
    assert "def compose" not in src, "bank must not expose compose(); rollout is sequential"


def test_eval_does_not_import_model_internals():
    """PLAN §4.F: eval depends on nothing but contracts.Policy."""
    ev = ROOT / "loom" / "eval"
    if not ev.exists():
        pytest.skip("eval not landed")
    offenders = []
    for p in ev.rglob("*.py"):
        for line in p.read_text().splitlines():
            s = line.strip()
            if not (s.startswith("import ") or s.startswith("from ")):
                continue          # lazy imports inside functions are allowed
            if "loom.model" in s or "loom.heads" in s or "loom.train" in s:
                offenders.append(f"{p.relative_to(ROOT)}: {s}")
    assert not offenders, "eval must couple only to contracts.Policy:\n" + "\n".join(offenders)


def test_sbatch_files_name_only_real_partitions():
    """batch_block1/2/3 do not exist on this cluster; naming one is a 0-second
    job failure that looks like a code bug."""
    files = list((ROOT / "loom" / "train" / "slurm").glob("*.sbatch")) if \
        (ROOT / "loom" / "train" / "slurm").exists() else []
    files += list((ROOT / "scripts").glob("*.sbatch")) if (ROOT / "scripts").exists() else []
    if not files:
        pytest.skip("no sbatch files landed")
    for f in files:
        src = f.read_text()
        for ghost in ("batch_block1", "batch_block2", "batch_block3"):
            assert ghost not in src, f"{f.name} names nonexistent partition {ghost}"
